sap.ui.define([                                                                                                                                                                                                                                                
	"sap/ui/core/mvc/Controller"                                                                                                                                                                                                                                  
], function (Controller) {                                                                                                                                                                                                                                     
	"use strict";                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                               
	return Controller.extend("ZINFRA_MRS_PLANNING_BOARD.ZINFRA_MRS_PLANNING_BOARD.controller.DailyView", {                                                                                                                                                        
                                                                                                                                                                                                                                                               
		/**                                                                                                                                                                                                                                                          
		 * Called when a controller is instantiated and its View controls (if available) are already created.                                                                                                                                                        
		 * Can be used to modify the View before it is displayed, to bind event handlers and do other one-time initialization.                                                                                                                                       
		 * @memberOf ZINFRA_MRS_PLANNING_BOARD.ZINFRA_MRS_PLANNING_BOARD.view.DailyView                                                                                                                                                                              
		 */                                                                                                                                                                                                                                                          
		onInit: function () {                                                                                                                                                                                                                                        
			sap.ui.core.UIComponent.getRouterFor(this).attachRouteMatched(this.onRouteMatched, this);                                                                                                                                                                   
		},                                                                                                                                                                                                                                                           
		onRouteMatched: function (oSelModel) {                                                                                                                                                                                                                       
			// ===============================================                                                                                                                                                                                                          
			var that = this;                                                                                                                                                                                                                                            
			var oFilter = new sap.ui.model.Filter("SelFilters", "EQ", oSelModel.getParameter("arguments").selModel);                                                                                                                                                    
			var oOperationsView =                                                                                                                                                                                                                                       
				new sap.m.PlanningCalendarView({                                                                                                                                                                                                                           
					key: "7",                                                                                                                                                                                                                                                 
					intervalType: sap.ui.unified.CalendarIntervalType.Day,                                                                                                                                                                                                    
					intervalsS: 7,                                                                                                                                                                                                                                            
					intervalsM: 7,                                                                                                                                                                                                                                            
					intervalsL: 7,                                                                                                                                                                                                                                            
					showSubIntervals: false                                                                                                                                                                                                                                   
				});                                                                                                                                                                                                                                                        
			var oAllocationsView =                                                                                                                                                                                                                                      
				new sap.m.PlanningCalendarView({                                                                                                                                                                                                                           
					key: "7",                                                                                                                                                                                                                                                 
					intervalType: sap.ui.unified.CalendarIntervalType.Day,                                                                                                                                                                                                    
					intervalsS: 7,                                                                                                                                                                                                                                            
					intervalsM: 7,                                                                                                                                                                                                                                            
					intervalsL: 7,                                                                                                                                                                                                                                            
					showSubIntervals: false                                                                                                                                                                                                                                   
				});                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                               
			this.byId("idDailyViewOperations").addView(oOperationsView);                                                                                                                                                                                                
			this.byId("idDailyViewOperations").setViewKey("7");                                                                                                                                                                                                         
			this.byId("idDailyViewAllocations").addView(oAllocationsView);                                                                                                                                                                                              
			this.byId("idDailyViewAllocations").setViewKey("7");                                                                                                                                                                                                        
                                                                                                                                                                                                                                                               
			var oOperationsModel = new sap.ui.model.json.JSONModel();                                                                                                                                                                                                   
			var oAllocationsModel = new sap.ui.model.json.JSONModel();                                                                                                                                                                                                  
			this.byId("idDailyViewOperations").setModel(oOperationsModel, "operationsModel");                                                                                                                                                                           
			this.byId("idDailyViewAllocations").setModel(oAllocationsModel, "allocationsModel");                                                                                                                                                                        
			this.getView().getModel("DataProvider").read(                                                                                                                                                                                                               
				"/DailyViewSet", {                                                                                                                                                                                                                                         
					urlParameters: {                                                                                                                                                                                                                                          
						"$expand": "DailyView_Sections/Section_OperAllocs"                                                                                                                                                                                                       
					},                                                                                                                                                                                                                                                        
					filters: [oFilter],                                                                                                                                                                                                                                       
					success: function (oData, oResponse) {                                                                                                                                                                                                                    
						oOperationsModel.setData(oData.results[0]);                                                                                                                                                                                                              
						oAllocationsModel.setData(oData.results[1]);                                                                                                                                                                                                             
						// Fill Assignment Data for Operations                                                                                                                                                                                                                   
						that.byId("idDailyViewOperations").rerender();                                                                                                                                                                                                           
						that._addOperAllocDetails($(".sapUiCalendarAppTitleWrapper").children());                                                                                                                                                                                
                                                                                                                                                                                                                                                               
					}                                                                                                                                                                                                                                                         
				}                                                                                                                                                                                                                                                          
			);                                                                                                                                                                                                                                                          
			// ===============================================                                                                                                                                                                                                          
			// window.setInterval(function () {                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                               
			// }, 5000);                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                               
		},                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
		onCalendarPanning: function () {                                                                                                                                                                                                                             
			// ===============================================                                                                                                                                                                                                          
			// Synchronise Panning                                                                                                                                                                                                                                      
			this.byId("idDailyViewAllocations").setStartDate(this.byId("idDailyViewOperations").getStartDate());                                                                                                                                                        
			// Refill Assignment data for operations                                                                                                                                                                                                                    
			this.byId("idDailyViewOperations").rerender();                                                                                                                                                                                                              
			this._addOperAllocDetails($(".sapUiCalendarAppTitleWrapper").children());                                                                                                                                                                                   
			// ===============================================                                                                                                                                                                                                          
		},                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
		onSelNDays: function (oEvtSelDays) {                                                                                                                                                                                                                         
			// ===============================================                                                                                                                                                                                                          
			var nDays;                                                                                                                                                                                                                                                  
			switch (oEvtSelDays.getParameter("item").getKey()) {                                                                                                                                                                                                        
			case "7":                                                                                                                                                                                                                                                   
				nDays = 7;                                                                                                                                                                                                                                                 
				break;                                                                                                                                                                                                                                                     
			case "14":                                                                                                                                                                                                                                                  
				nDays = 14;                                                                                                                                                                                                                                                
				break;                                                                                                                                                                                                                                                     
			case "21":                                                                                                                                                                                                                                                  
				nDays = 21;                                                                                                                                                                                                                                                
				break;                                                                                                                                                                                                                                                     
			}                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
			// Synchronise Panning                                                                                                                                                                                                                                      
			this.byId("idDailyViewAllocations").setStartDate(this.byId("idDailyViewOperations").getStartDate());                                                                                                                                                        
                                                                                                                                                                                                                                                               
			this.byId("idDailyViewOperations").destroyViews();                                                                                                                                                                                                          
			this.byId("idDailyViewAllocations").destroyViews();                                                                                                                                                                                                         
                                                                                                                                                                                                                                                               
			this.byId("idDailyViewOperations").addView(                                                                                                                                                                                                                 
				new sap.m.PlanningCalendarView({                                                                                                                                                                                                                           
					key: oEvtSelDays.getParameter("item").getKey(),                                                                                                                                                                                                           
					intervalType: sap.ui.unified.CalendarIntervalType.Day,                                                                                                                                                                                                    
					intervalsS: nDays,                                                                                                                                                                                                                                        
					intervalsM: nDays,                                                                                                                                                                                                                                        
					intervalsL: nDays,                                                                                                                                                                                                                                        
					showSubIntervals: false                                                                                                                                                                                                                                   
				})                                                                                                                                                                                                                                                         
			);                                                                                                                                                                                                                                                          
			this.byId("idDailyViewAllocations").addView(                                                                                                                                                                                                                
				new sap.m.PlanningCalendarView({                                                                                                                                                                                                                           
					key: oEvtSelDays.getParameter("item").getKey(),                                                                                                                                                                                                           
					intervalType: sap.ui.unified.CalendarIntervalType.Day,                                                                                                                                                                                                    
					intervalsS: nDays,                                                                                                                                                                                                                                        
					intervalsM: nDays,                                                                                                                                                                                                                                        
					intervalsL: nDays,                                                                                                                                                                                                                                        
					showSubIntervals: false                                                                                                                                                                                                                                   
				})                                                                                                                                                                                                                                                         
			);                                                                                                                                                                                                                                                          
			this.byId("idDailyViewOperations").setViewKey(oEvtSelDays.getParameter("item").getKey());                                                                                                                                                                   
			this.byId("idDailyViewAllocations").setViewKey(oEvtSelDays.getParameter("item").getKey());                                                                                                                                                                  
                                                                                                                                                                                                                                                               
			this.byId("idDailyViewOperations").rerender();                                                                                                                                                                                                              
			this._addOperAllocDetails($(".sapUiCalendarAppTitleWrapper").children());                                                                                                                                                                                   
			// ===============================================                                                                                                                                                                                                          
		},                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
		_addOperAllocDetails: function (oHtml) {                                                                                                                                                                                                                     
			// ===============================================                                                                                                                                                                                                          
			// Buffer Operations in View                                                                                                                                                                                                                                
			var oOperations =                                                                                                                                                                                                                                           
				this.byId("idDailyViewOperations").getModel("operationsModel").getData()                                                                                                                                                                                   
				.DailyView_Sections.results[0]                                                                                                                                                                                                                             
				.Section_OperAllocs.results;                                                                                                                                                                                                                               
			var span;                                                                                                                                                                                                                                                   
			var sHtml;                                                                                                                                                                                                                                                  
			//Return the JSON Node with the Matching Operation in the title                                                                                                                                                                                             
			var fOperAlloc = function (oOperAlloc) {                                                                                                                                                                                                                    
				return oOperAlloc.Operresource === oHtml[span].previousElementSibling.innerText;                                                                                                                                                                           
			};                                                                                                                                                                                                                                                          
			//Return the JSON Node with the Matching Start date in the Appointment                                                                                                                                                                                      
			var fDate = function (oOperAlloc) {                                                                                                                                                                                                                         
				return (oOperAlloc.Operallocstart.getDate().toString().padStart(2, "0") + "/" +                                                                                                                                                                            
						(oOperAlloc.Operallocstart.getMonth() + 1).toString().padStart(2, "0") + "/" +                                                                                                                                                                           
						oOperAlloc.Operallocstart.getFullYear().toString()) ===                                                                                                                                                                                                  
					(oHtml[span].offsetParent.children[1].innerText.split(";")[0].substr(oHtml[                                                                                                                                                                               
							span].offsetParent.children[1].innerText                                                                                                                                                                                                                
						.split(";")[0].length - 25).substr(0, 10));                                                                                                                                                                                                              
			};                                                                                                                                                                                                                                                          
			for (span = 0; span < oHtml.length; span++) {                                                                                                                                                                                                               
				if (oHtml[span].className === "sapUiCalendarAppText" && oHtml[span].previousElementSibling.className === "sapUiCalendarAppTitle") {                                                                                                                        
					//HTML from Back-end for Current appointment                                                                                                                                                                                                              
					sHtml = "";                                                                                                                                                                                                                                               
					sHtml = oOperations.filter(fOperAlloc).find(fDate).Operallocdetails;                                                                                                                                                                                      
					if (sHtml) {                                                                                                                                                                                                                                              
						//Insert HTML below the text of the appointment                                                                                                                                                                                                          
						oHtml[span].insertAdjacentHTML("beforeEnd", sHtml);                                                                                                                                                                                                      
					}                                                                                                                                                                                                                                                         
				}                                                                                                                                                                                                                                                          
			}                                                                                                                                                                                                                                                           
			// ===============================================                                                                                                                                                                                                          
		},                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
		// Back to Selection Screen                                                                                                                                                                                                                                  
		onNavBackDailyView: function () {                                                                                                                                                                                                                            
			sap.ui.core.UIComponent.getRouterFor(this).navTo("toSelectionView", true);                                                                                                                                                                                  
		}                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                               
	});                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
});                                                                                                                                                                                                                                                            