/* global QUnit */                                                                                                                                                                                                                                             
QUnit.config.autostart = false;                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                               
sap.ui.getCore().attachInit(function () {                                                                                                                                                                                                                      
	"use strict";                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                               
	sap.ui.require([                                                                                                                                                                                                                                              
		"ZINFRA_MRS_PLANNING_BOARD/ZINFRA_MRS_PLANNING_BOARD/test/integration/AllJourneys"                                                                                                                                                                           
	], function () {                                                                                                                                                                                                                                              
		QUnit.start();                                                                                                                                                                                                                                               
	});                                                                                                                                                                                                                                                           
});                                                                                                                                                                                                                                                            